sampleproject/sampleapp/urls.py
from django.urls import path

from sampleapp import views

# name space - to avoid name conflict
app_name = 'sampleapp'

urlpatterns = [
    path('', views.fun1, name='fun'),
    path('movies/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add_details, name='add_details'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

sampleproject/sampleproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sampleproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sampleapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sampleproject/sampleapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='picture')

    def __str__(self):
        return self.name

sampleproject/sampleapp/forms.py
from django import forms
from . models import Movie
class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

sampleproject/sampleapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import Movieform

# Create your views here.
def fun1(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html',context)
# def details(request, movie_id):
#     return HttpResponse('this is movie number %s' % movie_id)

def details(request, movie_id):
    movie = Movie.objects.get(id = movie_id)
    return render(request, 'nexpage.html', {'obj':movie})
def add_details(request):
    if request.method == 'POST':
        name = request.POST['name']
        desc = request.POST['desc']
        year = request.POST['year']
        img = request.FILES['img']
        movies = Movie(name=name,desc=desc,year=year,img=img)
        movies.save()
    return render(request, 'add_details.html')
def update(request,id):
    movie = Movie.objects.get(id=id)
    form = Movieform(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'movie':movie,'form':form})
def delete(request,id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

sampleproject/templates/add_details.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter the movie name"><br><br>
    <input type="text" name="desc" placeholder="enter the movie description"><br><br>
    <input type="text" name="year" placeholder="enter the year"><br><br>
    <input type="file" name="img"><br><br>
    <button>Submit</button>
</form>
{% endblock %}

sampleproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'style1.css' %}" rel="stylesheet">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
<br>
{% block body %}
{% endblock %}
</body>
</html>

sampleproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Do you want to delete?
    <input type="submit">
</form>

sampleproject/templates/edit.html
{% load static %}
<link href="{% static 'style.css' %}" rel="stylesheet">
<form class="editpage" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

sampleproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<!--{% for movie in movie_list %}-->
<!--{{movie.id}}&#45;&#45;&ndash;&gt;{{movie.name}}<br>-->
<!--{% endfor %}-->
<!--{% for movie in movie_list %}-->
<!--<a href="movies/{{movie.id}}/" >{{movie.id}}&#45;&#45;&ndash;&gt;{{movie.name}}<br>-->
<!--{% endfor %}-->
<!--Web APP- url setup-->
<!--{% for movie in movie_list %}-->
<!--<img src="{{movie.img.url}}" width="100" height="100">-->
<!--<a href="{% url 'sampleapp:details' movie.id %}">{{movie.id}}&#45;&#45;&ndash;&gt;{{movie.name}}<br>-->
<!--{% endfor %}-->


<div class="container">
    <div class="row">
        {% for movie in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
              <img class="card-img-top" src="{{movie.img.url}}" style=height:400px;">
              <div class="card-body">
                <h5 class="card-title">{{movie.name}}</h5>
<!--                <p class="card-text">{{movie.desc}}</p>-->
                <a href="{% url 'sampleapp:details' movie.id %}" class="btn btn-primary">More details</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

sampleproject/templates/nexpage.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src=" {{obj.img.url}} " width="300" height="300">
        </div>
        <div class="col-md-6">
            <h4>{{obj.name}}</h4>
            <h6>{{obj.desc}}</h6>
            <h6>{{obj.year}}</h6>
            <a class="btn btn-warning" href="{% url 'sampleapp:update' obj.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'sampleapp:delete' obj.id %}">Delete</a>

        </div>
    </div>
</div>




<!--{{obj.name}}<br>-->
<!--{{obj.desc}}<br>-->
<!--{{obj.year}}<br>-->
<!--<img src=" {{obj.img.url}} " width="100" height="100"><br>-->
<!--<a class="btn btn-warning" href="{% url 'sampleapp:update' obj.id %}">Update</a><br>-->
<!--<a class="btn btn-danger" href="{% url 'sampleapp:delete' obj.id %}">Delete</a><br>-->
{% endblock %}